### PR TITLE
fix: :pencil2: fixed little misunderstandings

### PR DESCRIPTION
**Pull request by Tahinli**
i did some minimal fixes to make understanding better.

### CODE REVIEW

**Comment by elevenhsoft** [comment]
Thank you!

I did some changes and added new translations, if you would like to complete this file, please take a look on master: https://github.com/elevenhsoft/WebApps/blob/master/i18n/en/webapps.ftl there is few more :)

**Comment by Tahinli** [comment]
> Thank you!
> 
> I did some changes and added new translations, if you would like to complete this file, please take a look on master: https://github.com/elevenhsoft/WebApps/blob/master/i18n/en/webapps.ftl there is few more :)

I'm checking immediately.

**Comment by Tahinli** [comment]
Can you check, is there a part that I missed ?

**Comment by elevenhsoft** [comment]
Should be fine. If you are OK with the result :) Thank you again :)

**Comment by elevenhsoft** [comment]
btw. the update on flathub should be tomorrow.

**Comment by Tahinli** [comment]
Please let me know, if you add another parts to translate.

**Comment by elevenhsoft** [comment]
Sure!

**Pull request merged**
