### PR TITLE
Create Italian language (it)

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by elevenhsoft** [comment]
Hello,

Thank you so much for your contribution! :)

**Comment by elevenhsoft** [comment]
Well, you should put this file in directory matching you language code. I guess it's `it`

Can you correct it with this path: `i18n/it/webapps.ftl`, please?

**Comment by albanobattistella** [comment]
> Well, you should put this file in directory matching you language code. I g

Hi, 
I tried but I can't.

**Comment by elevenhsoft** [comment]
> > Well, you should put this file in directory matching you language code. I g
> 
> Hi, I tried but I can't.



> > Well, you should put this file in directory matching you language code. I g
> 
> Hi, I tried but I can't.



> > Well, you should put this file in directory matching you language code. I g
> 
> Hi, I tried but I can't.

No problem. I corrected it. 

Thank you again, and hope you like this app :)

**Pull request merged**
